// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlzNigtlhRmcxZtMo3QHy3SIAaY-IzRDA',
    appId: '1:1078261651972:web:f01f52b6cdcf8bb2ebb351',
    messagingSenderId: '1078261651972',
    projectId: 'noteapp-96ab0',
    authDomain: 'noteapp-96ab0.firebaseapp.com',
    storageBucket: 'noteapp-96ab0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqKtGRPeIiqxZu7sEozlDDqten-lqUq8',
    appId: '1:1078261651972:android:51e7e6a4d08bcf88ebb351',
    messagingSenderId: '1078261651972',
    projectId: 'noteapp-96ab0',
    storageBucket: 'noteapp-96ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD53aRPvaXSslKB75zGgKZGAqHVUpLebK8',
    appId: '1:1078261651972:ios:99519de0d89a5f61ebb351',
    messagingSenderId: '1078261651972',
    projectId: 'noteapp-96ab0',
    storageBucket: 'noteapp-96ab0.appspot.com',
    iosBundleId: 'gatiella.app.noteapp',
  );
}
